using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.Extensions.Options;
using Scriban.Runtime;
using StrongLink.Worker.Configuration;
using StrongLink.Worker.Domain;
using StrongLink.Worker.Localization;
using StrongLink.Worker.QuestionProviders.Prompts;
using StrongLink.Worker.Services;

namespace StrongLink.Worker.QuestionProviders;

public sealed class AiQuestionProvider : IQuestionProvider
{
    private readonly HttpClient _httpClient;
    private readonly OpenAiOptions _options;
    private readonly ILocalizationService _localizationService;
    private readonly ILogger<AiQuestionProvider> _logger;

    public AiQuestionProvider(
        HttpClient httpClient,
        IOptions<OpenAiOptions> options,
        ILocalizationService localizationService,
        ILogger<AiQuestionProvider> logger)
    {
        _httpClient = httpClient;
        _options = options.Value;
        _localizationService = localizationService;
        _logger = logger;
    }

    public QuestionSourceMode Mode => QuestionSourceMode.AI;

    /// <summary>
    /// Selects a topic with configurable probability from suggested topics list vs random/new AI-generated topic
    /// </summary>
    /// <param name="suggestedTopics">List of suggested topics</param>
    /// <param name="probability">Probability (0.0-1.0) of selecting from suggested topics. Default 0.5 (50/50)</param>
    /// <param name="random">Random generator (optional)</param>
    /// <returns>Selected topic string, or empty string if AI should generate a random topic</returns>
    public static string SelectTopicWithProbability(
        IReadOnlyList<string> suggestedTopics,
        double probability = 0.5,
        Random? random = null)
    {
        random ??= Random.Shared;

        // Clamp probability between 0 and 1
        probability = Math.Clamp(probability, 0.0, 1.0);

        // Check if we should use a suggested topic
        if (suggestedTopics.Count > 0 && random.NextDouble() <= probability)
        {
            var index = random.Next(suggestedTopics.Count);
            return suggestedTopics[index];
        }

        // Use a random topic (will be generated by AI)
        return string.Empty; // Empty string signals AI to generate its own topic
    }

    public async Task<IReadOnlyDictionary<int, List<Question>>> PrepareQuestionPoolAsync(
        IReadOnlyList<string> topics,
        int tours,
        int roundsPerTour,
        IReadOnlyList<Player> players,
        GameLanguage language,
        bool matureContent,
        CancellationToken cancellationToken)
    {
        return await PrepareQuestionPoolAsync(topics, tours, roundsPerTour, players, language, matureContent, null, DifficultyLevel.Easy, cancellationToken);
    }

    public async Task<IReadOnlyDictionary<int, List<Question>>> PrepareQuestionPoolAsync(
        IReadOnlyList<string> topics,
        int tours,
        int roundsPerTour,
        IReadOnlyList<Player> players,
        GameLanguage language,
        bool matureContent,
        IReadOnlyList<Question>? archivedQuestions,
        CancellationToken cancellationToken)
    {
        return await PrepareQuestionPoolAsync(topics, tours, roundsPerTour, players, language, matureContent, archivedQuestions, DifficultyLevel.Easy, cancellationToken);
    }

    public async Task<IReadOnlyDictionary<int, List<Question>>> PrepareQuestionPoolAsync(
        IReadOnlyList<string> topics,
        int tours,
        int roundsPerTour,
        IReadOnlyList<Player> players,
        GameLanguage language,
        bool matureContent,
        IReadOnlyList<Question>? archivedQuestions,
        DifficultyLevel difficultyLevel,
        CancellationToken cancellationToken)
    {
        var result = new Dictionary<int, List<Question>>();

        for (var tourIndex = 0; tourIndex < tours; tourIndex++)
        {
            try
            {
                var topicOrNull = topics.ElementAtOrDefault(tourIndex);
                var isRandomTopic = string.IsNullOrEmpty(topicOrNull);
                var topic = isRandomTopic ? "random" : topicOrNull;

                var questionsNeeded = Math.Max(1, players.Count) * roundsPerTour;
                _logger.LogInformation("Requesting {Count} AI questions for topic {Topic} (random: {IsRandom})",
                    questionsNeeded, topic, isRandomTopic);

                var questionList = await GenerateInChunksAsync(
                    language, topic!, questionsNeeded, matureContent, difficultyLevel,
                    archivedQuestions, isRandomTopic, cancellationToken);

                _logger.LogInformation("Total questions collected for tour {Tour}: {Count} (requested {Needed})",
                    tourIndex + 1, questionList.Count, questionsNeeded);

                result[tourIndex + 1] = questionList;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to generate questions for tour {Tour}", tourIndex + 1);
                result[tourIndex + 1] = new List<Question>();
            }
        }

        return result;
    }

    /// <summary>
    /// Generates questions in chunks of at most <see cref="MaxChunkSize"/> per request to avoid
    /// hitting the HttpClient timeout with large prompts.
    /// </summary>
    private async Task<List<Question>> GenerateInChunksAsync(
        GameLanguage language,
        string topic,
        int totalNeeded,
        bool matureContent,
        DifficultyLevel difficultyLevel,
        IReadOnlyList<Question>? archivedQuestions,
        bool isRandomTopic,
        CancellationToken cancellationToken)
    {
        const int MaxChunkSize = 10;

        var collected = new List<Question>();
        // Keep a running exclusion set so successive chunks don't repeat each other either.
        var baseExclusions = archivedQuestions?.TakeLast(200).ToList() ?? new List<Question>();

        var remaining = totalNeeded;
        while (remaining > 0 && !cancellationToken.IsCancellationRequested)
        {
            var chunkSize = Math.Min(remaining, MaxChunkSize);

            // Merge base exclusions with already-collected questions for dedup.
            var exclusionsForChunk = new List<Question>(baseExclusions);
            exclusionsForChunk.AddRange(collected);

            var prompt = BuildPrompt(language, topic, chunkSize, matureContent, difficultyLevel,
                exclusionsForChunk, isRandomTopic);
            _logger.LogDebug("Chunk prompt (need {ChunkSize} of {Remaining} remaining): {Prompt}", chunkSize, remaining, prompt);

            var response = await RequestOpenAiAsync(prompt, cancellationToken);
            // Empty topic → SanitizeTopicName returns "General"; avoids "random" leaking into TopicSelector.
            var topicForStorage = isRandomTopic ? string.Empty : topic;
            var parsed = ParseQuestions(response, topicForStorage).ToList();
            _logger.LogInformation("Chunk returned {Count} questions (requested {ChunkSize})", parsed.Count, chunkSize);

            if (parsed.Count == 0)
            {
                // OpenAI returned nothing useful — stop to avoid an infinite loop.
                _logger.LogWarning("Empty chunk response for topic '{Topic}'. Stopping early with {Count}/{Total} questions.",
                    topic, collected.Count, totalNeeded);
                break;
            }

            collected.AddRange(parsed);
            remaining -= parsed.Count;
        }

        return collected;
    }

    internal string BuildPrompt(GameLanguage language, string topic, int questions, bool matureContent, DifficultyLevel difficultyLevel, IReadOnlyList<Question>? archivedQuestions = null, bool isRandomTopic = false)
    {
        // How many questions should carry an image URL.
        var questionsWithImages = (int)Math.Ceiling(questions * _options.ImagePercentage / 100.0);

        // Assemble the archived-question exclusion list (data shaping stays in C#; the template just
        // iterates the resulting formatted strings). Prefer topic-specific questions, backfilled with
        // general ones when the topic-specific set is small.
        var archivedLines = BuildArchivedExclusionList(topic, archivedQuestions);

        // Movie/film topics get extra genre guidance in the template.
        var isMovieTopic = !isRandomTopic && (
            topic.Contains("кино", StringComparison.OrdinalIgnoreCase) ||
            topic.Contains("фильм", StringComparison.OrdinalIgnoreCase) ||
            topic.Contains("movie", StringComparison.OrdinalIgnoreCase) ||
            topic.Contains("cinema", StringComparison.OrdinalIgnoreCase) ||
            topic.Contains("film", StringComparison.OrdinalIgnoreCase));

        var fileName = language == GameLanguage.Russian
            ? "QuestionGeneration.ru.scriban"
            : "QuestionGeneration.en.scriban";

        var model = new ScriptObject
        {
            ["topic"] = topic,
            ["questions"] = questions,
            ["questions_with_images"] = questionsWithImages,
            ["difficulty"] = difficultyLevel.ToString(),
            ["mature"] = matureContent,
            ["is_random_topic"] = isRandomTopic,
            ["is_movie_topic"] = isMovieTopic,
            ["archived"] = archivedLines
        };

        return PromptTemplateLoader.Render(fileName, model);
    }

    /// <summary>
    /// Builds the formatted "already used" exclusion list from archived questions. Topic-specific
    /// questions come first; if fewer than 20 match, general questions are appended for extra
    /// coverage. Returns an empty list when there is nothing to exclude.
    /// </summary>
    private List<string> BuildArchivedExclusionList(string topic, IReadOnlyList<Question>? archivedQuestions)
    {
        if (archivedQuestions is null || archivedQuestions.Count == 0)
        {
            return new List<string>();
        }

        // Case-insensitive topic matching.
        var topicLower = topic.ToLowerInvariant();
        var relevantQuestions = archivedQuestions
            .Where(q => !string.IsNullOrEmpty(q.Topic) && q.Topic.ToLowerInvariant().Contains(topicLower))
            .TakeLast(200)
            .Select(q => $"- {q.Text} → {q.Answer}")
            .ToList();

        _logger.LogInformation("Found {Count} archived questions for topic '{Topic}' to exclude from generation",
            relevantQuestions.Count, topic);

        if (relevantQuestions.Count < 20)
        {
            var generalQuestions = archivedQuestions
                .Where(q => string.IsNullOrEmpty(q.Topic) || !q.Topic.ToLowerInvariant().Contains(topicLower))
                .TakeLast(30)
                .Select(q => $"- {q.Text} → {q.Answer}")
                .ToList();

            _logger.LogInformation("Adding {Count} general archived questions to exclusion list", generalQuestions.Count);
            relevantQuestions.AddRange(generalQuestions);
        }

        return relevantQuestions;
    }

    private async Task<OpenAiResponse> RequestOpenAiAsync(string prompt, CancellationToken cancellationToken)
    {
        const int MaxAttempts = 5;
        var delays = new[] { 15, 30, 60, 120 }; // seconds between retries

        for (var attempt = 1; attempt <= MaxAttempts; attempt++)
        {
            try
            {
                using var request = new HttpRequestMessage(HttpMethod.Post, _options.Endpoint);
                request.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", _options.ApiKey);

                var body = new OpenAiRequest
                {
                    Model = _options.Model,
                    Messages =
                    [
                        new OpenAiMessage("system", PromptTemplateLoader.Render("QuestionGenerationSystem.scriban")),
                        new OpenAiMessage("user", prompt)
                    ]
                };

                var json = JsonSerializer.Serialize(body, new JsonSerializerOptions
                {
                    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
                });

                request.Content = new StringContent(json, System.Text.Encoding.UTF8, "application/json");

                _logger.LogDebug("Sending request to OpenAI (attempt {Attempt}/{Max}): {Endpoint}", attempt, MaxAttempts, _options.Endpoint);
                using var response = await _httpClient.SendAsync(request, cancellationToken);

                if (response.StatusCode == System.Net.HttpStatusCode.TooManyRequests ||
                    response.StatusCode == System.Net.HttpStatusCode.ServiceUnavailable)
                {
                    if (attempt == MaxAttempts)
                    {
                        var errBody = await response.Content.ReadAsStringAsync(cancellationToken);
                        _logger.LogError("OpenAI rate limit hit on final attempt. Status: {Status}, Body: {Body}", response.StatusCode, errBody);
                        response.EnsureSuccessStatusCode();
                    }

                    // Honour Retry-After header if present, otherwise use exponential backoff
                    var waitSeconds = delays[attempt - 1];
                    if (response.Headers.RetryAfter?.Delta is TimeSpan retryDelta)
                        waitSeconds = Math.Max(waitSeconds, (int)Math.Ceiling(retryDelta.TotalSeconds));
                    else if (response.Headers.RetryAfter?.Date is DateTimeOffset retryDate)
                        waitSeconds = Math.Max(waitSeconds, (int)Math.Ceiling((retryDate - DateTimeOffset.UtcNow).TotalSeconds));

                    _logger.LogWarning("OpenAI rate limit (attempt {Attempt}/{Max}). Retrying in {Wait}s...", attempt, MaxAttempts, waitSeconds);
                    await Task.Delay(TimeSpan.FromSeconds(waitSeconds), cancellationToken);
                    continue;
                }

                if (!response.IsSuccessStatusCode)
                {
                    var errorContent = await response.Content.ReadAsStringAsync(cancellationToken);
                    _logger.LogError("OpenAI API returned {StatusCode}: {Error}", response.StatusCode, errorContent);
                    response.EnsureSuccessStatusCode();
                }

                var payload = await JsonSerializer.DeserializeAsync<OpenAiResponse>(
                    await response.Content.ReadAsStreamAsync(cancellationToken),
                    cancellationToken: cancellationToken);
                return payload ?? throw new InvalidOperationException("OpenAI response payload was null");
            }
            catch (HttpRequestException ex)
            {
                if (attempt == MaxAttempts)
                {
                    _logger.LogError(ex, "HTTP request to OpenAI failed after {Max} attempts", MaxAttempts);
                    throw;
                }
                var waitSeconds = delays[attempt - 1];
                _logger.LogWarning(ex, "HTTP request to OpenAI failed (attempt {Attempt}/{Max}). Retrying in {Wait}s...", attempt, MaxAttempts, waitSeconds);
                await Task.Delay(TimeSpan.FromSeconds(waitSeconds), cancellationToken);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to request questions from OpenAI");
                throw;
            }
        }

        throw new InvalidOperationException("Unreachable: exceeded retry loop without returning or throwing");
    }

    private IEnumerable<Question> ParseQuestions(OpenAiResponse response, string topic)
    {
        var content = response.Choices.Select(c => c.Message.Content).FirstOrDefault() ?? string.Empty;

        _logger.LogInformation("OpenAI response content:\n{Content}", content);

        var lines = content.Split('\n', StringSplitOptions.RemoveEmptyEntries);
        _logger.LogInformation("Split into {Count} lines", lines.Length);

        string? questionText = null;
        string? answerText = null;
        string? imageUrl = null;
        var parsedCount = 0;

        foreach (var line in lines)
        {
            var trimmedLine = line.Trim();
            _logger.LogDebug("Processing line: {Line}", trimmedLine);

            if (trimmedLine.StartsWith("Question:", StringComparison.OrdinalIgnoreCase) ||
                trimmedLine.StartsWith("Вопрос:", StringComparison.OrdinalIgnoreCase) ||
                trimmedLine.StartsWith("Q:", StringComparison.OrdinalIgnoreCase))
            {
                // If we have a pending question without an image line, yield it now
                if (!string.IsNullOrWhiteSpace(questionText) && !string.IsNullOrWhiteSpace(answerText))
                {
                    parsedCount++;
                    _logger.LogDebug("Successfully parsed question #{Count} (no image)", parsedCount);
                    yield return new Question
                    {
                        Topic = topic,
                        Text = questionText + '?',
                        Answer = answerText,
                        SourceName = "OpenAI",
                        ImageUrl = null
                    };
                }

                var colonIndex = trimmedLine.IndexOf(':');
                questionText = trimmedLine[(colonIndex + 1)..].Trim().TrimEnd('?');
                answerText = null;
                imageUrl = null;
                _logger.LogDebug("Found question: {Question}", questionText);
            }
            else if (trimmedLine.StartsWith("Answer:", StringComparison.OrdinalIgnoreCase) ||
                     trimmedLine.StartsWith("Ответ:", StringComparison.OrdinalIgnoreCase) ||
                     trimmedLine.StartsWith("A:", StringComparison.OrdinalIgnoreCase))
            {
                var colonIndex = trimmedLine.IndexOf(':');
                answerText = trimmedLine[(colonIndex + 1)..].Trim().TrimEnd('.');
                _logger.LogDebug("Found answer: {Answer}", answerText);
            }
            else if (trimmedLine.StartsWith("Image:", StringComparison.OrdinalIgnoreCase) ||
                     trimmedLine.StartsWith("Изображение:", StringComparison.OrdinalIgnoreCase))
            {
                var colonIndex = trimmedLine.IndexOf(':');
                imageUrl = trimmedLine[(colonIndex + 1)..].Trim();
                _logger.LogDebug("Found image URL: {ImageUrl}", imageUrl);

                // Yield the question with the image
                if (!string.IsNullOrWhiteSpace(questionText) && !string.IsNullOrWhiteSpace(answerText))
                {
                    parsedCount++;
                    _logger.LogDebug("Successfully parsed question #{Count} with image", parsedCount);
                    yield return new Question
                    {
                        Topic = topic,
                        Text = questionText + '?',
                        Answer = answerText,
                        SourceName = "OpenAI",
                        ImageUrl = imageUrl
                    };

                    questionText = null;
                    answerText = null;
                    imageUrl = null;
                }
            }
        }

        // Handle last question if it doesn't have an image line
        if (!string.IsNullOrWhiteSpace(questionText) && !string.IsNullOrWhiteSpace(answerText))
        {
            parsedCount++;
            _logger.LogDebug("Successfully parsed final question #{Count} (no image)", parsedCount);
            yield return new Question
            {
                Topic = topic,
                Text = questionText + '?',
                Answer = answerText,
                SourceName = "OpenAI",
                ImageUrl = null
            };
        }

        _logger.LogInformation("Total questions parsed: {Count}", parsedCount);
    }

    /// <summary>
    /// Generates an image for a question using DALL-E API.
    /// This is an optional enhancement that can be enabled via configuration.
    /// </summary>
    private async Task<string?> GenerateImageWithDallEAsync(Question question, CancellationToken cancellationToken)
    {
        if (!_options.UseDallEImageGeneration)
        {
            return null;
        }

        try
        {
            _logger.LogInformation("Generating DALL-E image for question: {Question}", question.Text);

            // Create a descriptive prompt for DALL-E based on the question
            var imagePrompt = $"A clear, simple, educational illustration for a trivia question about: {question.Text}. " +
                            $"The image should help visualize the concept related to the answer: {question.Answer}. " +
                            "Style: clean, educational, suitable for all ages, no text in image.";

            using var request = new HttpRequestMessage(HttpMethod.Post, _options.DallEEndpoint);
            request.Headers.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", _options.ApiKey);

            var body = new DallERequest
            {
                Model = _options.DallEModel,
                Prompt = imagePrompt,
                N = 1,
                Size = _options.DallEImageSize
            };

            var json = JsonSerializer.Serialize(body, new JsonSerializerOptions
            {
                DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
            });

            request.Content = new StringContent(json, System.Text.Encoding.UTF8, "application/json");

            _logger.LogDebug("Sending DALL-E request: {Endpoint}", _options.DallEEndpoint);
            using var response = await _httpClient.SendAsync(request, cancellationToken);

            if (!response.IsSuccessStatusCode)
            {
                var errorContent = await response.Content.ReadAsStringAsync(cancellationToken);
                _logger.LogWarning("DALL-E API returned {StatusCode}: {Error}", response.StatusCode, errorContent);
                return null; // Gracefully fail - question will have no image
            }

            var payload = await JsonSerializer.DeserializeAsync<DallEResponse>(
                await response.Content.ReadAsStreamAsync(cancellationToken),
                cancellationToken: cancellationToken);

            var imageUrl = payload?.Data?.FirstOrDefault()?.Url;
            if (!string.IsNullOrWhiteSpace(imageUrl))
            {
                _logger.LogInformation("Successfully generated DALL-E image: {Url}", imageUrl);
                return imageUrl;
            }

            _logger.LogWarning("DALL-E response did not contain an image URL");
            return null;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to generate image with DALL-E for question: {Question}", question.Text);
            return null; // Gracefully fail - question will have no image
        }
    }

    private sealed record OpenAiRequest
    {
        [JsonPropertyName("model")]
        public required string Model { get; init; }

        [JsonPropertyName("messages")]
        public required IReadOnlyList<OpenAiMessage> Messages { get; init; }
    }

    private sealed record OpenAiMessage(
        [property: JsonPropertyName("role")] string Role,
        [property: JsonPropertyName("content")] string Content);

    private sealed record OpenAiResponse
    {
        [JsonPropertyName("choices")]
        public required IReadOnlyList<Choice> Choices { get; init; }

        public sealed record Choice
        {
            [JsonPropertyName("message")]
            public required OpenAiMessage Message { get; init; }
        }
    }

    private sealed record DallERequest
    {
        [JsonPropertyName("model")]
        public required string Model { get; init; }

        [JsonPropertyName("prompt")]
        public required string Prompt { get; init; }

        [JsonPropertyName("n")]
        public int N { get; init; }

        [JsonPropertyName("size")]
        public required string Size { get; init; }
    }

    private sealed record DallEResponse
    {
        [JsonPropertyName("data")]
        public IReadOnlyList<DallEImageData>? Data { get; init; }

        public sealed record DallEImageData
        {
            [JsonPropertyName("url")]
            public string? Url { get; init; }
        }
    }
}

